d <- read.table("household_power_consumption.txt", sep=";", fill=FALSE, strip.white=TRUE, header = TRUE, na.strings = "?")
d$Date <- as.Date(d$Date, "%d/%m/%Y")
d <- subset(d, (Date == as.Date("2007-02-01") | Date == as.Date("2007-02-02")))
d$Datetime <- paste(d$Date, d$Time)
d$Datetime <- as.POSIXct(strftime(d$Datetime, format = "%Y-%m-%d %H:%M:%S", tz="", usetz = FALSE))
plot(d$Datetime, d$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(d$Datetime, d$Sub_metering_2, col="red")
lines(d$Datetime, d$Sub_metering_3, col="blue")
legend("topright",c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),lty=c(1,1,1), col = c("black", "red", "blue"))
dev.copy(png, file = "plot3.png")
dev.off()